WIP: main/master handling

diff --git a/omgf b/omgf
--- a/omgf
+++ b/omgf
@@ -10,6 +10,8 @@ set -u
 # shellcheck disable=SC2086
 : ${OMGF_VERSION:=VERSION}
 # shellcheck disable=SC2086
+: ${OMGF_MASTER:=main}
+# shellcheck disable=SC2086
 : ${OMGF_DEV:=dev}
 # shellcheck disable=SC2086
 : ${OMGF_ORIGIN:=origin}
@@ -325,7 +327,7 @@ function main {
   }
 
   function master_last_change {
-    git cherry -v "$OMGF_DEV" master | tail -n1 | cut -d" " -f2
+    git cherry -v "$OMGF_DEV" "$OMGF_MASTER" | tail -n1 | cut -d" " -f2
   }
 
   # $1 filepath
@@ -384,7 +386,7 @@ function main {
   # 1) validate repository existence
   # 2) validate repository consistency:
   # - at least one commit
-  # - master branch
+  # - main/master branch
   function validate_git_repository {
     if ! git_repo_exists; then
       [[ $conform == 0 ]] && { err "Git repository does not exist" || return 3; }
@@ -395,9 +397,13 @@ function main {
     if ! git_has_commits; then
       [[ $conform == 0 ]] && { err "Git repository without commits" || return 3; }
       initial_commit || return $?
-    elif ! git_local_branch_exists master; then
-      [[ $conform == 0 ]] && { err "Missing branch 'master'" || return 3; }
-      git_branch_create master || return 1
+    elif ! git_local_branch_exists $OMGF_MASTER || ! git_local_branch_exists main; then
+      [[ $conform == 0 ]] && { err "Missing branch 'main' or 'master'" || return 3; }
+      git_branch_create $OMGF_MASTER || return 1
+    fi
+    # If old naming used, fill correct name
+    if git_local_branch_exists master; then
+      OMGF_MASTER="master"
     fi
   }
 
@@ -411,7 +417,7 @@ function main {
 
   # validate tag on ($)master
   function validate_master_tag {
-    if ([[ $1 == master ]] || [[ $1 == "$master" ]]) && ! git_tag_here "$master.$patch"; then
+    if ([[ $1 == $OMGF_MASTER ]] || [[ $1 == "$master" ]]) && ! git_tag_here "$master.$patch"; then
       [[ $conform == 0 ]] && { err "Missing tag '$master.$patch' on current HEAD" || return 3; }
       git_tag "$master.$patch";
     fi
@@ -422,12 +428,12 @@ function main {
   function validate_dev {
     if ! git_local_branch_exists "$OMGF_DEV"; then
       [[ $conform == 0 ]] && { err "Missing branch '$OMGF_DEV'" || return 3; }
-      git_branch_create dev master || return 1
+      git_branch_create $OMGF_DEV $OMGF_MASTER || return 1
     fi
     local last_change
     last_change="$(master_last_change)"
     if [[ -n "$last_change" ]] && ! git branch --contains "$last_change" | grep -q "$OMGF_DEV"; then
-      [[ $conform == 0 ]] && { err "Branch master is not merged with '$OMGF_DEV'" || return 3; }
+      [[ $conform == 0 ]] && { err "Branch '$OMGF_MASTER' is not merged with '$OMGF_DEV'" || return 3; }
       merge_branches "$last_change" "$OMGF_DEV" || return $?
     fi
   }
@@ -520,8 +526,8 @@ function main {
   }
 
   function create_stable_branch {
-    git_commit_diff "$gf_branch" master \
-      || { git_checkout master; return $?; }
+    git_commit_diff "$gf_branch" $OMGF_MASTER \
+      || { git_checkout $OMGF_MASTER; return $?; }
     if git_branch_exists "$master"; then
       git_commit_diff "$gf_branch" "$master" \
         || { git_checkout "$master"; return $?; }
@@ -538,7 +544,7 @@ function main {
     # action according to current branch
     if [[ $arg_count -eq 0 ]]; then
       case "${gf_branch%%-*}" in
-        HEAD|master|$prefix+([0-9]).+([0-9]))
+        HEAD|$OMGF_MASTER|$prefix+([0-9]).+([0-9]))
           branch_name="$(prefix_branch "$HOTFIX" "$(strtolower "$(whoami)")" )"
           gf_hotfix "$branch_name"
         ;;
@@ -574,7 +580,7 @@ function main {
     # action according to given name and kw
     if [[ -z "$par_kw" ]]; then
       case "${gf_branch%%-*}" in
-        HEAD|master|$prefix+([0-9]).+([0-9])|$RELEASE|$HOTFIX) par_kw="$HOTFIX" ;;
+        HEAD|$OMGF_MASTER|$prefix+([0-9]).+([0-9])|$RELEASE|$HOTFIX) par_kw="$HOTFIX" ;;
         $OMGF_DEV|$FEATURE) par_kw="$FEATURE" ;;
         *) err "Current branch '$gf_branch' is not recognized" || return 1 ;;
       esac
@@ -622,8 +628,8 @@ function main {
       confirmed=1
     fi
     # HEAD and master has no diff, nothing to do
-    [[ -n "$(git diff HEAD master)" ]] \
-      || err "Current HEAD is same as branch 'master', nothing to do" \
+    [[ -n "$(git diff HEAD '$OMGF_MASTER')" ]] \
+      || err "Current HEAD is same as branch '$OMGF_MASTER', nothing to do" \
       || return 1
     [[ $confirmed == 0 ]] \
       && { confirm "* Create branch '$RELEASE' from current HEAD?" || return 0; }
@@ -670,7 +676,7 @@ function main {
       hotfix_name="$1"
     fi
     to="$( git tag | grep -e ^"$master". | sort -V | tail -n1 )"
-    [ -z "$to" ] && to="master"
+    [ -z "$to" ] && to="$OMGF_MASTER"
     if git_branch_exists "$hotfix_name"; then
       gf_confirm_checkout "$hotfix_name"
       return $?
@@ -679,7 +685,7 @@ function main {
     gf_checkout "$to" \
       && load_version \
       || return $?
-    if [[ "$gf_branch" != master ]]; then
+    if [[ "$gf_branch" != $OMGF_MASTER ]]; then
       create_stable_branch || return $?
     fi
     git_checkout_branch "$hotfix_name" || return $?
@@ -694,11 +700,11 @@ function main {
     local confirm_suffix
     [[ $request == 1 ]] && confirm_suffix="$pr_suffix" || confirm_suffix=
     confirm "* Create stable branch from release$confirm_suffix?" || return 0
-    merge_branches master "$gf_branch" || return $?
-    [[ $request == 1 ]] && { gf_request master; return $?; }
-    git_checkout master \
+    merge_branches "$OMGF_MASTER" "$gf_branch" || return $?
+    [[ $request == 1 ]] && { gf_request "$OMGF_MASTER"; return $?; }
+    git_checkout $OMGF_MASTER \
       && merge_branches "$gf_branch" "$OMGF_DEV" \
-      && merge_branches "$gf_branch" master \
+      && merge_branches "$gf_branch" "$OMGF_MASTER" \
       && git_tag "$master".0 \
       && delete_gf_branch \
       && git_checkout "$OMGF_DEV" \
@@ -790,10 +796,10 @@ function main {
   function gf_write_changelog_line {
     local tmpfile compare_url
     tmpfile="$(mktemp)"
-    compare_url="$(gf_get_compare_url master "$OMGF_DEV")"
+    compare_url="$(gf_get_compare_url "$OMGF_MASTER" "$OMGF_DEV")"
     [[ -n "$compare_url" ]] \
       && compare_url="[Unreleased]: $compare_url" \
-      || compare_url="[Unreleased]: master..$OMGF_DEV"
+      || compare_url="[Unreleased]: $OMGF_MASTER..$OMGF_DEV"
     gawk -v keyword="$1" -v next_keywords="$2" -v message="$3" -v compare_url="$compare_url" '
       function print_unreleased () { print "## [Unreleased]" }
       function print_keyword () { print "### " keyword }
@@ -944,8 +950,8 @@ function main {
     [[ $request == 1 ]] && confirm_suffix="$pr_suffix" || confirm_suffix=
     # master -> merge hotfix into master and dev
     #if ! git_version_diff master "$major.$minor"; then
-      into=master
-      confirm "* Merge hotfix into master and '$OMGF_DEV'$confirm_suffix?" || return 0
+      into="$OMGF_MASTER"
+      confirm "* Merge hotfix into '$OMGF_MASTER' and '$OMGF_DEV'$confirm_suffix?" || return 0
     #else
     #  into="$master"
     #  confirm "* Merge hotfix into stable branch '$master'$confirm_suffix?" || return 0
@@ -964,7 +970,7 @@ function main {
         || return $?
     fi
     [[ $request == 1 ]] && { gf_request "$into"; return $?; }
-    if [[ "$into" == master ]]; then
+    if [[ "$into" == $OMGF_MASTER ]]; then
       # ignore changes in VERSION file iff conflict occured
       if git_branch_exists "$RELEASE"; then
         gf_version_ignore_merge "$OMGF_DEV" \
@@ -1009,7 +1015,7 @@ function main {
     git_remote_exists \
       && git_fetch --tags \
       && gf_pull_branch "$OMGF_DEV" \
-      && gf_pull_branch master \
+      && gf_pull_branch "$OMGF_MASTER" \
       && gf_pull_branch "$RELEASE" \
       || return $?
     local stable
@@ -1023,7 +1029,7 @@ function main {
     git_remote_exists \
       && git_push --tags \
       && git_push "$OMGF_ORIGIN" "$OMGF_DEV" \
-      && git_push "$OMGF_ORIGIN" master \
+      && git_push "$OMGF_ORIGIN" "$OMGF_MASTER" \
       || return $?
     git_local_branch_exists "$RELEASE" \
       && { git_push "$OMGF_ORIGIN" "$RELEASE" || return $?; }
@@ -1141,7 +1147,7 @@ function main {
     gcb=$(git_current_branch)
     echo -n "* Current branch '$gcb' is considered as "
     case $gcb in
-      HEAD|master|$prefix+([0-9]).+([0-9]))
+      HEAD|$OMGF_MASTER|$prefix+([0-9]).+([0-9]))
         if gf_hotfixable 2>/dev/null; then
           echo "hotfixable stable branch."
           echo "* - Run '$script_name' to create hotfix or leave :)"
